export const provinces = [
  { id: 1, province: "a_coruna", name: "A Coruña" },
  { id: 2, province: "alava", name: "Álava" },
  { id: 3, province: "albacete", name: "Albacete" },
  { id: 4, province: "alicante", name: "Alicante" },
  { id: 5, province: "almeria", name: "Almería" },
  { id: 6, province: "asturias", name: "Asturias" },
  { id: 7, province: "avila", name: "Ávila" },
  { id: 8, province: "badajoz", name: "Badajoz" },
  { id: 9, province: "baleares", name: "Baleares" },
  { id: 10, province: "barcelona", name: "Barcelona" },
  { id: 11, province: "burgos", name: "Burgos" },
  { id: 12, province: "caceres", name: "Cáceres" },
  { id: 13, province: "cadiz", name: "Cádiz" },
  { id: 14, province: "cantabria", name: "Cantabria" },
  { id: 15, province: "castellón", name: "Castellón" },
  { id: 16, province: "ciudad_real", name: "Ciudad Real" },
  { id: 17, province: "cordoba", name: "Córdoba" },
  { id: 18, province: "cuenca", name: "Cuenca" },
  { id: 19, province: "girona", name: "Gerona" },
  { id: 20, province: "granada", name: "Granada" },
  { id: 21, province: "guadalajara", name: "Guadalajara" },
  { id: 22, province: "gipuzkoa", name: "Guipúzcoa" },
  { id: 23, province: "huelva", name: "Huelva" },
  { id: 24, province: "huesca", name: "Huesca" },
  { id: 25, province: "jaén", name: "Jaén" },
  { id: 26, province: "la_rioja", name: "La Rioja" },
  { id: 27, province: "las_palmas", name: "Las Palmas" },
  { id: 28, province: "león", name: "León" },
  { id: 29, province: "lérida", name: "Lérida" },
  { id: 30, province: "lugo", name: "Lugo" },
  { id: 31, province: "madrid", name: "Madrid" },
  { id: 32, province: "malaga", name: "Málaga" },
  { id: 33, province: "murcia", name: "Murcia" },
  { id: 34, province: "navarra", name: "Navarra" },
  { id: 35, province: "ourense", name: "Ourense" },
  { id: 36, province: "palencia", name: "Palencia" },
  { id: 37, province: "pontevedra", name: "Pontevedra" },
  { id: 38, province: "salamanca", name: "Salamanca" },
  { id: 39, province: "segovia", name: "Segovia" },
  { id: 40, province: "sevilla", name: "Sevilla" },
  { id: 41, province: "soria", name: "Soria" },
  { id: 42, province: "tarragona", name: "Tarragona" },
  {
    id: 43,
    province: "santa_cruz_de_tenerife",
    name: "Santa Cruz de Tenerife"
  },
  { id: 44, province: "teruel", name: "Teruel" },
  { id: 45, province: "toledo", name: "Toledo" },
  { id: 46, province: "valencia", name: "Valencia" },
  { id: 47, province: "valladolid", name: "Valladolid" },
  { id: 48, province: "vizcaya", name: "Vizcaya" },
  { id: 49, province: "zamora", name: "Zamora" },
  { id: 50, province: "zaragoza", name: "Zaragoza" }
];
